# Generated by Django 6.0.1 on 2026-02-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title',
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(default='Неизвестно', max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(default='Тур по горам', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='relation_db.person'),
        ),
    ]
