# Generated by Django 6.0.1 on 2026-02-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0002_remove_tour_description_remove_tour_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.TextField(default='Неизвестно', max_length=100),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=100)),
                ('text', models.CharField(default='Очень ответственный человек', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='relation_db.person')),
            ],
        ),
    ]
