# Generated by Django 6.0.1 on 2026-02-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0003_alter_tour_location_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.ManyToManyField(null=True, to='relation_db.category'),
        ),
    ]
