# Generated by Django 6.0.1 on 2026-02-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='напишите названия книги')),
                ('description', models.TextField(verbose_name='напишите аннотацию книги')),
                ('image', models.ImageField(upload_to='booklist/', verbose_name='загрузите фото')),
                ('created_data_lang', models.PositiveBigIntegerField(blank=True, verbose_name='укажите год создания книги')),
                ('chapter_count', models.PositiveIntegerField(verbose_name='сколько глва в книге')),
                ('author', models.CharField(max_length=100, verbose_name='автор книги')),
                ('pages', models.PositiveIntegerField(verbose_name='количество страниц')),
                ('language', models.CharField(max_length=50, verbose_name='язык книги')),
                ('publisher', models.CharField(max_length=100, verbose_name='издательство')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
