# Generated by Django 6.0.1 on 2026-02-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='chapter_count',
            field=models.PositiveIntegerField(verbose_name='сколько глав в книге'),
        ),
    ]
