# Generated by Django 6.0.1 on 2026-02-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_booklist_chapter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
