# Generated by Django 6.0.1 on 2026-02-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResuMe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Бишкек', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=200, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], default='MALE', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='+996', max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resume_users/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Навыки'),
        ),
    ]
