# Generated by Django 6.0.1 on 2026-02-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResuMe', '0002_alter_customuser_birthday_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='+996', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
