# Generated by Django 6.0.1 on 2026-02-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResuMe', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.TextField(verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.TextField(verbose_name='Навыки'),
        ),
    ]
